title: M.N. Roberts Technical Resume
author: Nikki Roberts
email: Nikki-Roberts@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  A techincal resume for Nikki Roberts.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
